fos_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            toolbar: [[ "Format", "Bold", "Italic", "Link", "Unlink", "BulletedList", "NumberedList", "BlockQuote", "Image" ]]
            format_tags: 'p;h1;h2;h3;h4;h5;h6'
            